theme: jekyll-theme-minimal
title: Advancing Technology in the Star City
description: >
  Noke Codes is a civic-minded technology organization aimed at building a stronger
  communityhere in the Roanoke Valley through technology. We want to celebrate the 
  technical capacity of our community while also striving to make it even better.
