theme: jekyll-theme-minimal
title: Noke Codes | Advancing Technology in the Star City
description: Noke Codes is a civic-minded technology organization aimed at building a stronger community here in the Roanoke Valley through technology.
